---
- name: Install packages
  apt:
    name:
      - net-tools
      - mc
      - vim
      - git
      - bash-completion
      - python3
      - tar
      - rsyslog
    state: latest

- name: Enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Check is swap enable
  shell: swapon
  register: swap_present
  changed_when: false
  ignore_errors: true

- name: If swap is enabled - disable it
  shell: swapoff -a
  when: swap_present.stdout != ""

- name: Disable SWAP in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s*swap\s*.*)$'
    replace: '# \1'
