apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: juice
  name: juice
spec:
  imagePullSecrets:
  - name: juiceshop-secret
  containers:
  - image: harbor.local/juiceshop/juiceshop:1.1
    name: juice
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
